name: mytransportation
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: any
  flutter_map_marker_cluster: ^1.4.0
  fuzzywuzzy: ^1.2.0
  geolocator: ^13.0.2
  http: ^1.2.2
  latlong2: ^0.9.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
